name: ShopLocal CI/CD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧼 Lint
        run: npm run lint || echo "Lint warnings only"

      - name: 🧪 Test
        run: npm test || echo "No tests yet – skipping"

      - name: 🛠 Build
        run: npm run build

      - name: 🚀 Deploy (placeholder)
        run: echo "Ready for S3 deployment"
